.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.travis.yml
CHANGELOG.md
README.md
defaults/main.yml
molecule.yml
tasks/deploy.yml
tasks/main.yml
tests/Dockerfile
tests/test_ansible.py

##Added
- List of remote wars to deploy
- List of local (control machine) wars to deploy
- add two task on a `deploy.yml` file with _deploy_ task

#1 add deploy task

---

tasks/config.yml

Fixes #6 
As usual, works in local, Travis says nope.

Fix extra conf templates src and dest

---

CHANGELOG.md
defaults/main.yml
tasks/deploy.yml

fixes #13 
Now, maven repository can be used as remote war source

Include maven repository as remote war source

---

CHANGELOG.md
tasks/deploy.yml

add owner and group on depoy tasks

---

LICENSE
meta/main.yml

#36 using idealista S.A.U. instead of idealista S.A.

---

CHANGELOG.md
defaults/main.yml

Updated tomcat version to 8.5.28 (latest)
http://tomcat.apache.org/tomcat-8.5-doc/changelog.html#Tomcat_8.5.28_(markt)

[#46] Updated tomcat version to 8.5.28

---

CHANGELOG.md
defaults/main.yml
templates/setenv.sh.j2

Updated tomcat version to 8.5.29 (latest)
http://tomcat.apache.org/tomcat-8.5-doc/changelog.html#Tomcat_8.5.29_(markt)

[#49] Update tomcat version to 8.5.29

---

CHANGELOG.md
defaults/main.yml
tasks/config.yml
tasks/install.yml
templates/setenv.sh.j2

release 1.7.0

---

.travis.yml
CHANGELOG.md
README.md
defaults/main.yml
molecule/agent/requirements.yml
molecule/change-log-path/requirements.yml
molecule/default/requirements.yml
tasks/deploy.yml
test-requirements.txt

Add Ansible 2.6 support for module maven_artifact

---

CHANGELOG.md
defaults/main.yml
molecule/default/group_vars/tomcat/main.yml
tasks/agent.yml
templates/agents/version.txt.j2

Improved agents management.
The agent is downloaded and configured only when its needed.
#66

[#66] Improve agents management

---

.travis.yml
CHANGELOG.md
README.md
defaults/main.yml
molecule/default/molecule.yml
molecule/default/tests/test_tomcat.yml
molecule/default/verify.yml

As Tomcat 7.x and Tomcat 8.x are currently mantained versions of Tomcat, it would be nice to add scenarios testing that are supported versions that could be installed using this role. These versions should be explicitly specified as supported versions in the Readme file
#64

[#64] Adding testing scenarios for tomcat 7.x and 8.x

---

CHANGELOG.md
defaults/main.yml
templates/tomcat.service.j2

Improve systemd template adding limits
Limits can be modified.
#69

[#69] Improve systemd template adding limits

---

Pipfile
Pipfile.lock
test-requirements.txt

bump ansible to 2.8.8

---

.travis.yml
README.md
meta/main.yml
molecule/default/Dockerfile.j2
molecule/default/molecule.yml

Support and testing for debian (8,9,10) and ubuntu 20.04.
Tested with java8,java11 (debian) and java8/java14 in ubuntu.
#75

[#75] Support for debian buster

---

defaults/main.yml
molecule/default/group_vars/tomcat/main.yml
molecule/default/tests/test_tomcat.yml
tasks/deploy.yml

[#81] Add support to ansible 2.9x. Fixed package install

---

.travis.yml
CHANGELOG.md

Release 1.10.1

---

.travis.yml
CHANGELOG.md
Pipfile
Pipfile.lock
defaults/main.yml
molecule/default/Dockerfile.j2
molecule/default/group_vars/tomcat/main.yml
molecule/default/molecule.yml
molecule/default/templates/tomcat/agents/newrelic/extensions/extension-example.xml.j2
molecule/default/tests/test_tomcat.yml
molecule/default/verify.yml
tasks/agent.yml
test-requirements.txt

Changes needed to support extensions for java agents in this role.
Support for java agent extensions
#126

[#126] Agent extensions support

---

Pipfile.lock
defaults/main.yml
tasks/deploy.yml

Patch adds new feature to download extra jar files. For example, Tomcat application could require JDBC driver.

Add extra jar files download

---

Pipfile.lock
defaults/main.yml
templates/server.xml.j2

https://tomcat.apache.org/tomcat-8.5-doc/changelog.html

Apache Tomcat 8.5.51 adds a secret required attribute to the AJP Connector

---

CHANGELOG.md
tasks/agent.yml

[#129]  Agent extensions cleanup. fix for ansible <= 2.9
